options = trainingOptions("adam", ...
    "InitialLearnRate", 1e-4, ...
    "MaxEpochs", 10, ...
    "MiniBatchSize", 8, ...
    "Shuffle", "every-epoch", ...
    "ValidationData", augimdsVal, ...
    "ValidationFrequency", 50, ...
    "Verbose", true, ...
    "Plots", "training-progress", ...
    "ResetInputNormalization", false);